name: Build and publish

on:
  push:
    branches:
      - 3.x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build --stacktrace
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 8
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Publish
        run: chmod +x ./gradlew && ./gradlew publish && ./gradlew jreleaserFullRelease --stacktrace
        env:
          JRELEASER_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          JRELEASER_MAVENCENTRAL_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
          JRELEASER_MAVENCENTRAL_TOKEN: "${{ secrets.SONATYPE_PASSWORD }}"
          JRELEASER_NEXUS2_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
          JRELEASER_NEXUS2_TOKEN: "${{ secrets.SONATYPE_PASSWORD }}"
          JRELEASER_GPG_PUBLIC_KEY: "${{ secrets.SIGNING_PUBLIC_KEY }}"
          JRELEASER_GPG_SECRET_KEY: "${{ secrets.SIGNING_SECRET_KEY }}"
          JRELEASER_GPG_PASSPHRASE: "${{ secrets.SIGNING_PASSWORD }}"
